---
apiVersion: generators.external-secrets.io/v1alpha1
kind: UUID
metadata:
  name: uuid
spec: {}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulsar-pulsar-manager-secret
spec:
  refreshInterval: "0s"
  target:
    name: pulsar-pulsar-manager-secret
    template:
      data:
        DB_USERNAME: pulsar
        UI_USERNAME: pulsar
        UI_PASSWORD: '{{ randBytes 32  | sha256sum }}'
        DB_PASSWORD: '{{  randBytes 32 | sha256sum }}'
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: UUID
        name: "uuid"