victoria-metrics-k8s-stack:
  enabled: false

components:
  toolset: false
  # oxia: true
  functions: true
  dekaf: true

volumes:
  persistence: true


zookeeper:
  replicaCount: 1
  podMonitor:
    enabled: false
  volumes:
    data:
      size: 2Gi

oxia:
  coordinator:
    podMonitor:
      enabled: false
  server:
    podMonitor:
      enabled: false
      
bookkeeper:
  replicaCount: 1
  podMonitor:
    enabled: false
  volumes:
    useSingleCommonVolume: true
    common:
      size: 5Gi

autorecovery:
  podMonitor:
    enabled: false

broker:
  replicaCount: 1
  podMonitor:
    enabled: false
  configData:
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"


pulsar_manager:
  admin: 
    existingSecret: pulsar-pulsar-manager-secret

proxy:
  replicaCount: 1
  podMonitor:
    enabled: false

dekaf:
  persistence:
    enabled: false
  deployment:
    extraEnv:
    - name: DEKAF_BASE_PATH
      value: /dekaf
    - name: DEKAF_PUBLIC_BASE_URL
      value: https://pulsar.jynolen.fr/dekaf
    livenessProbe:
      httpGet:
        path: /dekaf/health
    readinessProbe:
      httpGet:
        path: /dekaf/health