---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc
  namespace: backbone
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-proxy
  oidc:
    provider:
      issuer: "https://casdoor.open.jynolen.fr/"
    clientID: "815d4d9da589b1f0ecc4"
    clientSecret:
      name: envoy-client-secret
    forwardAccessToken: false
    redirectURL: "https://envoy.jynolen.fr/oauth2/callback"
    cookieDomain: jynolen.fr
    cookieNames:
      accessToken: EnvoyAccessToken
      idToken: EnvoyIdToken
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: oidc
  namespace: backbone
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-proxy
  lua:
    - type: Inline
      inline: |
        local function split(str, delimiter)
            local returnTable = {}
            for k, v in string.gmatch(str or "", "([^" .. delimiter .. "]+)") 
            do
                returnTable[#returnTable+1] = k
            end
            return returnTable
        end

        local function tomap(tbl)
            local returnTable = {}
            for _, i in pairs(tbl or {}) do
                for k, v in string.gmatch(i, "(%w+)=(.+)") do
                    returnTable[k] = v
                end
            end
            return returnTable
        end
        
        function envoy_on_request(request_handle)
          c=tomap(split(request_handle:headers():get("cookie"), ";"))
          request_handle:headers():add("X-Auth-Token", c["EnvoyIdToken"] or "")
        end
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-redirect
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: ListenerSet
      name: envoy
  hostnames:
    - envoy.jynolen.fr
  rules:
    - matches:
        - path:
            type: Exact
            value: /oauth2/callback
      backendRefs:
        - group: ""
          kind: Service
          name: oidc-redirect
          port: 8080
