---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envoy-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: envoy-client-secret
    template:
      data:
        client-secret: '{{ .client_secret }}'
  data:
  - secretKey: client_secret
    remoteRef:
      key: /envoy/oidc-client-secret