application:
  namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

charts:
- repoURL: docker.io/envoyproxy
  chart: gateway-helm
  targetRevision: v1.7.1
  helm:
    skipCrds: true
- repoURL: docker.io/envoyproxy
  chart: gateway-crds-helm
  targetRevision: v0.0.0-latest
- repoURL: https://kfirfer.github.io/charts/
  chart: extra-manifests 
  targetRevision: 1.0.5
- repoURL: https://github.com/kubernetes-sigs/gateway-api
  path: config/crd
  targetRevision: v1.5.1