apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  config:
    server:
      root_url: https://observability.jynolen.fr/grafana  
      serve_from_sub_path: 'true'
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: jaeger
spec:
  datasource:
    name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686