apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: grafana-admin-password
    template:
      data:
        password: '{{ .uuid }}'
        username: admin
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid