apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarFunction
metadata:
  name: test-pulsar-function
spec:
  className: org.apache.pulsar.functions.api.examples.ExclamationFunction
  connectionRef:
    name: pulsar
  inputs:
  - otlp
  jar:
    url: function://public/default/api-examples@v3.2.3.3
  name: test-pulsar-function
  namespace: testns
  tenant: test
  output: dst
