appname = casdoor
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName = user={{ .username }} password={{ .password }} host={{ .host }} port={{ .port }} sslmode=disable dbname={{ .dbname }} 
dbName = {{ .dbname }} 
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = ""
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin =
enableGzip = true
ldapServerPort = 10389