write-kubeconfig-mode: "0644"
cluster-init: true
cluster-cidr: 172.20.0.0/16
service-cidr: 172.21.0.0/16
cluster-dns:  172.21.0.255
disable:
  - traefik
  - servicelb
  - local-storage
# MetalLB Address Pool 2a01:e0a:86b:72d1:0:2::/112