# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  reset:
    cmds:
      - k3s-killall.sh
      - k3s-lite-uninstall.sh
  k3s:
    deps:
    - reset
    cmds: 
    - cp k3s.config.yaml /etc/rancher/k3s/config.yaml
    - k3s
    - systemctl start k3s
  kubie:
    cmds:
      - sed "s/default/k3s/" /etc/rancher/k3s/k3s.yaml > ~/.kube/kubie/k3s.yaml
      - sed "s/default/k3s-root/" /etc/rancher/k3s/k3s.yaml > ~/.kube/config
    source:
    - /etc/rancher/k3s/k3s.yaml
  argocd:
    cmds:
    - kubectl get ns argocd || kubectl create ns argocd
    - kubectl apply -k argocd --server-side=true