apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubernetes-replicator

helmGlobals:
  chartHome: .charts

helmCharts:
- name: kubernetes-replicator
  version: v2.12.0
  repo: https://helm.mittwald.de
  releaseName: kubernetes-replicator
  includeCRDs: true

patches:
- target:
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true