---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pgbouncer-config
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          name: pgbouncer-config-tpl
          items:
          - key: pgbouncer.ini
            templateAs: Values
          - key: userlist.txt
            templateAs: Values
  dataFrom:
  - find:
      path: /aiven/psql