apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - image: docker.io/edoburu/pgbouncer:v1.25.1-p0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            tcpSocket:
              port: 5432
          name: pgbouncer
          ports:
            - containerPort: 5432
              name: psql
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: 5432
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 70
            runAsNonRoot: true
            runAsUser: 70
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/pgbouncer/
              name: config
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmp
        - name: config
          secret:
            secretName: pgbouncer-config
