apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipv6-pool
spec:
  addresses:
  - 2a01:e0a:86b:72d1:0:2::/112
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: expose
spec:
  ipAddressPools:
  - ipv6-pool
---