apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/tektoncd/pipeline/releases/download/v1.12.0/release.yaml

configMapGenerator:
- name: config-defaults 
  namespace: tekton-pipelines
  behavior: merge
  files:
  - default-pod-template=configs/default-pod-template