apiVersion: operator.tekton.dev/v1alpha1
kind: OpenShiftPipelinesAsCode
metadata:
  name: pipelines-as-code
spec:
  additionalPACControllers:
    controllername:
      enable: true
      configMapName:
      secretName:
      settings:
  enable: true
  settings:
    application-name: Pipelines as Code CI
    auto-configure-new-github-repo: "false"
    bitbucket-cloud-check-source-ip: "true"
    custom-console-name: ""
    custom-console-url: ""
    custom-console-url-pr-details: ""
    custom-console-url-pr-tasklog: ""
    error-detection-from-container-logs: "false"
    error-detection-max-number-of-lines: "50"
    error-detection-simple-regexp: ^(?P<filename>[^:]*):(?P<line>[0-9]+):(?P<column>[0-9]+):([]*)?(?P<error>.*)
    error-log-snippet: "true"
    error-log-snippet-number-of-lines: "3"
    enable-cancel-in-progress-on-pull-requests: "false"
    enable-cancel-in-progress-on-push: "false"
    hub-catalog-name: tekton
    hub-url: https://api.hub.tekton.dev/v1
    require-ok-to-test-sha: "false"
    skip-push-event-for-pr-commits: "true"
    remote-tasks: "true"
    secret-auto-create: "true"
    secret-github-app-token-scoped: "true"
  targetNamespace: tekton-pipelines