---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: admin
spec:
  passwordSecretKeyRef:
    name: mongodb-admin-password
    key: password
  username: admin
  db: admin
  mongodbResourceRef:
    name: mongo
  roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: readWrite
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-admin-password
spec:
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: mongodb-admin-password
    template:
      data:
        password: "{{.uuid}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
