apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmGlobals:
  chartHome: .charts

helmCharts:
- name: longhorn
  version: 1.11.1
  repo: https://charts.longhorn.io
  releaseName: longhorn
  includeCRDs: true
  additionalValuesFiles:
  - values.yaml

patches:
- target:
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true