apiVersion: v1
kind: List
items:
- apiVersion: frp.zufardhiyaulhaq.com/v1alpha1
  kind: Upstream
  metadata:
    name: echoserver-http
  spec:
    client: gw-tunnel
    http:
      host: echoserver.default.svc.cluster.local
      port: 80
      customDomains: &customDomains
        - srv630959.hstgr.cloud
        - 5b6c7180.nip.io
        - "*.5b6c7180.nip.io"
        - "*.jynolen.fr"
- apiVersion: frp.zufardhiyaulhaq.com/v1alpha1
  kind: Upstream
  metadata:
    name: echoserver-https
  spec:
    client: gw-tunnel
    https:
      host: echoserver.default.svc.cluster.local
      port: 80
      customDomains: *customDomains