apiVersion: frp.zufardhiyaulhaq.com/v1alpha1
kind: Upstream
metadata:
  name: echoserver
spec:
  client: gw-tunnel
  http:
    host: echoserver.default.svc.cluster.local
    port: 80
    customDomains:
      - 5b6c7180.nip.io
      - "*.5b6c7180.nip.io"
  https:
    host: echoserver.default.svc.cluster.local
    port: 80
    customDomains:
      - 5b6c7180.nip.io
      - "*.5b6c7180.nip.io"
  # tcp:
  #   host: echoserver.default.svc.cluster.local
  #   port: 80
  #   server:
  #     port: 80
  #   proxyProtocol: v2
  #   healthCheck:
  #     timeoutSeconds: 5
  #     maxFailed: 3
  #     intervalSeconds: 10
  #   transport:
  #     useEncryption: true
  #     useCompression: true
  #     bandwidthLimit:
  #       enabled: true
  #       limit: 1024
  #       type: MB