apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- workload.yaml
- service.yaml

images:
- name: github-webhook-validator
  newName: ghcr.io/johnvox/github-webhook-validator
  newTag: v1.0.1
