apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

labels:
- pairs:
    app.kubernetes.io/component: opentelemetry
    app.kubernetes.io/name: observability
  includeSelectors: true
  includeTemplates: true

configMapGenerator:
- name: opentelemetry-config
  files:
  - config/base.yaml
  - config/input.yaml
  - config/internal.yaml
  - config/output.splunk.yaml
  - config/output.pulsar.yaml
  - config/output.jaeger.yaml   
  - config/processor.argocd.yaml
  - config/processor.default.yaml
- name: opentelemetry-config-env
  literals:
  - OTEL_SELF_HEC_ENDPOINT=http://splunk.observability:8088

resources:
- rbac.yaml
- service.yaml
- workload.yaml

images:
- name: collector
  newName: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
  newTag: 0.151.0