apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-system

resources:
- crds

helmGlobals:
  chartHome: .charts

helmCharts:
- name: tigera-operator
  repo: https://docs.tigera.io/calico/charts
  version: 3.31.4
  releaseName: calico
  namespace: network-system
  additionalValuesFiles:
  - values.calico.yaml