apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-charts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      requeueAfterSeconds: 10
      repoURL: https://github.com/jynolen/perso-cluster.git
      revision: main
      files:
      - path: 'applications/backbone/*/kustomization.yaml'
      - path: 'applications/system/*/kustomization.yaml'
      - path: 'applications/client/*/kustomization.yaml'
      values:
        server: https://kubernetes.default.svc
  templatePatch: |
    {{- $annotations := dig "metadata" "annotations" (dict) -}}
    metadata:
      labels: {{. | dig "metadata" "labels" (dict) | toRawJson }}
      annotations:  {{. | dig "metadata" "annotations" (dict) | toRawJson }}
    spec:
      revisionHistoryLimit: {{ $annotations | get "argocd.argoproj.io/revisionHistoryLimit" | default 3 }}
      ignoreDifferences:
      {{- range $ignoreDiff := ($annotations | get "argocd.argoproj.io/ignoreDifferences" | default "[]"  | fromJson) }}
        - {{ $ignoreDiff }}
      {{- end }}
      sourceHydrator: {{  $annotations | get "argocd.argoproj.io/sourceHydrator" | default "{}" | fromJson | toRawJson }}
      {{- if  $annotations| hasKey "argocd.argoproj.io/syncPolicy"   }}
      syncPolicy: {{ $annotations | get "argocd.argoproj.io/syncPolicy" | fromJson | toRawJson }}
      {{- end }}
  template:
    metadata:
      name: '{{ index .path.segments 1 }}-{{ .path.basename }}'
    spec:
      project: application
      source:
        repoURL: https://github.com/jynolen/perso-cluster
        path: '{{ .path.path }}'
        targetRevision: '{{ . | dig "metadata" "annotations" "argocd.argoproj.io/revision" "HEAD" }}'
      destination:
        server: '{{ .values.server }}'
        namespace: '{{ coalesce (. | dig "namespace" nil) (. | dig "metadata" "annotations" "argocd.argoproj.io/namespace" nil ) }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace={{ coalesce (. | dig "namespace" nil) (. | dig "metadata" "annotations" "argocd.argoproj.io/namespace" nil ) | any }}
  syncPolicy:
    applicationsSync: create-update