apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations: 
    argocd.argoproj.io/revision: main

namespace: casdoor

labels:
- pairs:
    app.kubernetes.io/instance: casdoor
    app.kubernetes.io/name: casdoor
  includeSelectors: true
  includeTemplates: true

resources:
- workload.yaml
- service.yaml
- secrets.yaml
- route.yaml

configMapGenerator:
- name: casdoor-config-tpl
  files:
  - app.conf=config/app.conf.tpl
  options:
    disableNameSuffixHash: true