---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: casdoor
spec:
  data:
    host: pgbouncer.databases.svc.cluster.local
    username: casdoor
    port: '5432'
    dbname: casdoor
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: casdoor-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: casdoor-config
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          name: casdoor-config-tpl
          items:
          - key: app.conf
            templateAs: Values
  data:
  - secretKey: password
    remoteRef:
      key: /aiven/psql/casdoor
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Fake
        name: casdoor