apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
spec:
  mergeGateways: true
  logging:
    level:
      default: warn
  provider:
    kubernetes:
      envoyService:
        name: envoy-proxy
        externalTrafficPolicy: Local
        type: ClusterIP
      envoyDeployment:
        container: 
          image: docker.io/envoyproxy/envoy:distroless-v1.38.0
    type: Kubernetes
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-proxy
  annotations:
    external-dns.alpha.kubernetes.io/target: gw.jynolen.fr
    cert-manager.io/cluster-issuer: acme-issuer
spec:
  gatewayClassName: envoy-gateway
  allowedListeners:
    namespaces:
      from: All
  listeners:
  - name: http
    protocol: HTTP
    hostname: '*.jynolen.fr'
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-proxy-open
  annotations:
    external-dns.alpha.kubernetes.io/target: gw.jynolen.fr
    cert-manager.io/cluster-issuer: acme-issuer
spec:
  gatewayClassName: envoy-gateway
  allowedListeners:
    namespaces:
      from: All
  listeners:
  - name: open-http
    protocol: HTTP
    hostname: '*.open.jynolen.fr'
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
spec:
  parentRefs:
  - name: envoy-proxy
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: max-headers-patch-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: envoy-gateway
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: backbone/envoy-proxy/http
      operation:
        op: add
        jsonPath: "..filter_chains[].filters[].typed_config"
        path: "max_request_headers_kb"
        value: 256
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: backbone/envoy-proxy/backbone/envoy/envoy
      operation:
        op: add
        jsonPath: "..filter_chains[].filters[].typed_config"
        path: "max_request_headers_kb"
        value: 256