apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splunk-secret
spec:
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: splunk-secret
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "observability"
      data:
        masterPassword: "{{.password}}"
        hec_token: "{{ .uuid }}"
        pass4SymmKey: '{{ derivePassword 1 "maximum" .password "pass4SymmKey" "splunk" | sha256sum }}'
        password: '{{ derivePassword 1 "maximum" .password "password" "splunk" | sha256sum}}'
        idxc_secret: '{{ derivePassword 1 "maximum" .password "idxc" "splunk" | sha256sum }}'
        shc_secret: '{{ derivePassword 1 "maximum" .password "shc" "splunk" | sha256sum}}'
        default.yaml: |
          splunk:
              hec_disabled: 0
              hec_enableSSL: 0
              hec_token: {{ .uuid }}
              password: {{ derivePassword 1 "maximum" .password "password" "splunk" | sha256sum}}
              pass4SymmKey: {{ derivePassword 1 "maximum" .password "pass4SymmKey" "splunk" | sha256sum }}
              idxc:
                  secret: {{ derivePassword 1 "maximum" .password "idxc" "splunk" | sha256sum }}
              shc:
                  secret: {{ derivePassword 1 "maximum" .password "shc" "splunk" | sha256sum}}
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password
