exporters:
  pulsar:
    endpoint: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    topic: test/testns/otlp
    encoding: otlp_json
    timeout: 10s

service:
  pipelines:
    logs/pulsar:
      receivers:
      - forward/output
      exporters:
      - pulsar