apiVersion: v1
kind: Service
metadata:
  name: otel
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: jaeger-compact
      port: 6831
      protocol: UDP
      targetPort: jaeger-compact
    - name: jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: jaeger-grpc
    - name: jaeger-thrift
      port: 14268
      protocol: TCP
      targetPort: jaeger-thrift
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: otlp   
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
    - name: zipkin
      port: 9411
      protocol: TCP
      targetPort: zipkin
  sessionAffinity: None
  type: ClusterIP