apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/namespace: tekton
    argocd.argoproj.io/ignoreDifferences: '[{"group":"apiextensions.k8s.io","kind":"CustomResourceDefinition","jsonPointers":["/spec/preserveUnknownFields"]}]'

namespace: tekton-operator

resources:
- https://infra.tekton.dev/tekton-releases/operator/previous/v0.79.1/release.yaml
# - route.yaml

patches:
- target:
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true

# configMapGenerator:
# - name: pipelines-as-code
#   namespace: pipelines-as-code
#   behavior: merge
#   literals:
#   - tekton-dashboard-url=https://tekton.jynolen.fr/
#   options:
#     disableNameSuffixHash: true