apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/namespace: tekton-pipelines
    argocd.argoproj.io/ignoreDifferences: '[{"group":"apiextensions.k8s.io","kind":"CustomResourceDefinition","jsonPointers":["/spec/preserveUnknownFields"]}]'

resources:
- instance
- addons
- route.yaml
- secrets.yaml
- workload.yaml
- repos
- webhook.yaml

transformers:
- namespace.yaml

patches:
- target:
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true

images:
- name: github-webhook-validator
  newName: ghcr.io/johnvox/github-webhook-validator
  newTag: v1.0.1
