---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  parentRef:
    group: gateway.networking.k8s.io	
    kind: Gateway
    name: envoy-proxy
    namespace: backbone
  listeners:
  - name: tekton-auth-https
    protocol: HTTPS
    hostname: tekton.jynolen.fr
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: tekton-auth-jynolen-tls
        group: ''	
        kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: tekton-open
  namespace: tekton-pipelines
spec:
  parentRef:
    group: gateway.networking.k8s.io	
    kind: Gateway
    name: envoy-proxy-open
    namespace: backbone
  listeners:        
  - name: tekton-auth-https-webhook
    protocol: HTTPS
    hostname: webhook.tekton.jynolen.fr
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: webhook-tekton-auth-jynolen-tls
        group: ''	
        kind: Secret        
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: ListenerSet
      name: tekton
  hostnames:
  - tekton.jynolen.fr
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: tekton-dashboard
          port: 9097
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tekton-webhook
  namespace: tekton-pipelines
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: ListenerSet
      name: tekton-open
  hostnames:
  - webhook.tekton.jynolen.fr
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: pipelines-as-code-controller
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: webhook-validator-server
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: tekton-webhook
  extAuth:
    http:
      path: /webhook
      backendRef:
        name: github-webhook-validator
        port: 8080
      headersToBackend:
      - X-Hub-Signature-256
    headersToExtAuth:
    - X-Hub-Signature-256
    bodyToExtAuth:
      maxRequestBytes: 1048576