---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-as-code-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pipelines-as-code-secret
    template:
      data:
        github-private-key: '{{ .privateKey }}'
        github-application-id: '{{ .appId }}'
        webhook.secret: '{{ .webhookSecret }}'
  dataFrom:
  - find:
      path: /tekton