---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-webhook-validator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: github-token-validator
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: github-token-validator  
    spec:
      containers:
      - name: github-webhook-validator
        image: github-webhook-validator
        env:
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: webhook.secret
              name: pipelines-as-code-secret
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
            cpu: 100m
          requests:
            memory: 25Mi
            cpu: 50m
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 65532
          runAsGroup: 65532
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault            
---
apiVersion: v1
kind: Service
metadata:
  name: github-webhook-validator
spec:
  selector:
    app.kubernetes.io/name: github-token-validator
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
---
