apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: argocd-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/name: argocd-secret
        annotations:
          replicator.v1.mittwald.de/replicate-to: argocd
  dataFrom:
    - find:
        path: /argocd