# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: infisical-cloudflare-dns
# spec:
#   provider:
#     infisical:
#       hostAPI: https://eu.infisical.com/
#       auth:
#         jwtAuthCredentials:
#           identityId:
#             name: infisical-auth-credentials
#             key: identityId
#           jwt:
#             name: infisical-auth-credentials
#             key: jwt
#       secretsScope:
#         projectSlug: personnal-h-uas
#         environmentSlug: prod
#         recursive: true
#         secretsPath: /cloudflare/dns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-dns
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: external-dns
  dataFrom:
    - find:
        path: /cloudflare/dns