apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-dns
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: external-dns
  dataFrom:
    - find:
        path: /cloudflare/dns