---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-cloudflare-tunnel
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com/
      auth:
        jwtAuthCredentials:
          identityId:
            name: infisical-auth-credentials
            key: identityId
          jwt:
            name: infisical-auth-credentials
            key: jwt
      secretsScope:
        projectSlug: personnal-h-uas
        environmentSlug: prod
        recursive: true
        secretsPath: /cloudflare/tunnel
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-cloudflare-dns
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com/
      auth:
        jwtAuthCredentials:
          identityId:
            name: infisical-auth-credentials
            key: identityId
          jwt:
            name: infisical-auth-credentials
            key: jwt
      secretsScope:
        projectSlug: personnal-h-uas
        environmentSlug: prod
        recursive: true
        secretsPath: /cloudflare/dns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical-cloudflare-tunnel
  target:
    name: cloudflare-tunnel
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: cloudflared

  dataFrom:
    - find:
        name:
          regexp: .*
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical-cloudflare-dns
  target:
    name: cloudflare-dns
    template:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: external-dns,cert-manager
  dataFrom:
    - find:
        name:
          regexp: .*