---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com/
      auth:
        jwtAuthCredentials:
          identityId:
            name: infisical-auth-credentials
            key: identityId
            namespace: backbone
          jwt:
            name: infisical-auth-credentials
            key: jwt
            namespace: backbone
      secretsScope:
        projectSlug: personnal-h-uas
        environmentSlug: prod
        secretsPath: /
        recursive: true