---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-issue-self
  namespace: backbone
rules:
- verbs: ["create"]
  apiGroups: [""]
  resourceNames: ["infisical"]
  resources: ["serviceaccounts/token"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-issuer
subjects:
- kind: ServiceAccount
  name: default
  namespace: backbone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-issue-self
---
apiVersion: v1
kind: Secret
metadata:
  name: backbone-token-issuer-token
  labels:
    external-secrets.io/type: webhook
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
stringData:
  targetServiceAccount: infisical
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Webhook
metadata:
  name: webhook-token-request
spec:
  caProvider:
    type: ConfigMap
    name: kube-root-ca.crt
    key: ca.crt
  url: https://kubernetes.default.svc.cluster.local/api/v1/namespaces/{{ .auth.namespace }}/serviceaccounts/{{ .auth.targetServiceAccount}}/token
  method: POST
  result: 
    jsonPath: $.status
  body: | 
      {
        "kind": "TokenRequest",
        "apiVersion": "authentication.k8s.io/v1",
        "spec": {
          "expirationSeconds": 600,
          "audiences": ["https://kubernetes.default.svc.cluster.local", ""]
        }
      }
  headers:
    Content-Type: application/json
    Authorization: "Bearer {{ .auth.token }}"
  secrets:
  - name: auth
    secretRef:
      name: backbone-token-issuer-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-svc-acount
spec:
  refreshInterval: "9m"
  target:
    name: infisical-auth-credentials
    template:
      data:
        identityId: d80d1d8a-0ccc-4dbe-a9ad-288255a94d7a
        jwt: "{{ .token }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Webhook
        name: webhook-token-request
