apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

helmGlobals:
  chartHome: .charts

helmCharts:
- name: gateway-helm
  version: v1.8.0-rc.0
  repo: oci://docker.io/envoyproxy
  releaseName: envoy
  includeCRDs: false
  additionalValuesFiles:
  - values.yaml
- name: gateway-crds-helm
  version: v1.8.0-rc.0
  repo: oci://docker.io/envoyproxy
  releaseName: envoy-crds
  includeCRDs: true

patches:
- target:
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true